{'dataset_name': 'COLLAB', 'num_workers': 1, 'hyperparams': {'batch_size': 32, 'epochs': 351, 'learning_rate': 0.001, 'step_size': 20, 'decay_rate': 0.7}, 'architecture': {'layers': 3, 'hidden': 256, 'pooling': 'add', 'JK': 'cat', 'nonlinear_conv': 'EB3', 'dropout': 0.5, 'variants': {'BN': 'Y'}}, 'commit_id': '3f699c9289c8b0c796077e789b1b52d18fe3c5ff', 'time_stamp': '1605629529', 'directory': '../../nlg_results/tu/board/'}
-------- FOLD0 DATASET=COLLAB, COMMIT_ID=3f699c9289c8b0c796077e789b1b52d18fe3c5ff
Epoch: 001, Train Loss: 5.2369479, Train Acc: 0.6144444, Test Acc: 0.6040000
Epoch: 002, Train Loss: 2.7624481, Train Acc: 0.6628889, Test Acc: 0.6420000
Epoch: 003, Train Loss: 0.7844728, Train Acc: 0.6584444, Test Acc: 0.6380000
Epoch: 004, Train Loss: 1.1466964, Train Acc: 0.6564444, Test Acc: 0.6380000
Epoch: 005, Train Loss: 2.5699115, Train Acc: 0.6222222, Test Acc: 0.5600000
Epoch: 006, Train Loss: 2.0515559, Train Acc: 0.6600000, Test Acc: 0.6420000
Epoch: 007, Train Loss: 0.8416326, Train Acc: 0.7211111, Test Acc: 0.7120000
Epoch: 008, Train Loss: 0.7144326, Train Acc: 0.7037778, Test Acc: 0.6960000
Epoch: 009, Train Loss: 0.6731810, Train Acc: 0.7204444, Test Acc: 0.6880000
Epoch: 010, Train Loss: 0.7096450, Train Acc: 0.7104444, Test Acc: 0.6920000
Epoch: 011, Train Loss: 0.6935514, Train Acc: 0.6993333, Test Acc: 0.6780000
Epoch: 012, Train Loss: 1.2591586, Train Acc: 0.6833333, Test Acc: 0.6920000
Epoch: 013, Train Loss: 0.8968247, Train Acc: 0.6937778, Test Acc: 0.6720000
Epoch: 014, Train Loss: 0.6852441, Train Acc: 0.7211111, Test Acc: 0.7260000
Epoch: 015, Train Loss: 0.7432387, Train Acc: 0.6853333, Test Acc: 0.6680000
Traceback (most recent call last):
  File "./main.py", line 260, in <module>
    main()
  File "./main.py", line 256, in main
    run_model(NLG, dataset, config=config)
  File "./main.py", line 186, in run_model
    config=config
  File "./main.py", line 101, in run_given_fold
    train_loss = train(train_loader, model, optimizer)
  File "./main.py", line 65, in train
    output = model(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/GPUFS/dlut_bcyin_1/ymq/space/github_private/gnnzoo/tu/model.py", line 65, in forward
    x = conv(x, edge_index)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/GPUFS/dlut_bcyin_1/ymq/space/github_private/gnnzoo/tu/conv.py", line 33, in forward
    out = self.propagate(edge_index, x=x)
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 263, in propagate
    out = self.message(**msg_kwargs)
  File "/GPUFS/dlut_bcyin_1/ymq/space/github_private/gnnzoo/tu/conv.py", line 42, in message
    .transpose(-1, -2)).squeeze(-1).view(-1, self.hidden * self.num_aggr)
RuntimeError: CUDA out of memory. Tried to allocate 1.45 GiB (GPU 0; 15.75 GiB total capacity; 10.80 GiB already allocated; 1.23 GiB free; 13.43 GiB reserved in total by PyTorch)
