{'dataset_name': 'COLLAB', 'num_workers': 1, 'hyperparams': {'batch_size': 32, 'epochs': 201, 'learning_rate': 0.0005, 'step_size': 20, 'decay_rate': 0.7}, 'architecture': {'layers': 3, 'hidden': 256, 'pooling': 'add', 'JK': 'cat', 'nonlinear_conv': 'EB3', 'dropout': 0.5, 'variants': {'BN': 'Y'}}, 'commit_id': '9c82d98405370127a3f5465c3b0f11a933b0e688', 'time_stamp': '1605530231', 'directory': '../../nlg_results/tu/board/'}
-------- FOLD0 DATASET=COLLAB, COMMIT_ID=9c82d98405370127a3f5465c3b0f11a933b0e688
Epoch: 001, Train Loss: 2.6503417, Train Acc: 0.6200000, Test Acc: 0.6540000
Epoch: 002, Train Loss: 1.7536549, Train Acc: 0.6422222, Test Acc: 0.6820000
Epoch: 003, Train Loss: 1.6955094, Train Acc: 0.6448889, Test Acc: 0.6660000
Epoch: 004, Train Loss: 1.0419127, Train Acc: 0.6655556, Test Acc: 0.7000000
Epoch: 005, Train Loss: 1.9591750, Train Acc: 0.6755556, Test Acc: 0.6920000
Epoch: 006, Train Loss: 1.4235873, Train Acc: 0.6913333, Test Acc: 0.7000000
Traceback (most recent call last):
  File "./main.py", line 260, in <module>
    main()
  File "./main.py", line 256, in main
    run_model(NLG, dataset, config=config)
  File "./main.py", line 186, in run_model
    config=config
  File "./main.py", line 101, in run_given_fold
    train_loss = train(train_loader, model, optimizer)
  File "./main.py", line 65, in train
    output = model(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/GPUFS/dlut_bcyin_1/ymq/space/github_private/gnnzoo/tu/model.py", line 61, in forward
    x = conv(x, edge_index)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/GPUFS/dlut_bcyin_1/ymq/space/github_private/gnnzoo/tu/conv.py", line 33, in forward
    out = self.propagate(edge_index, x=x)
  File "/opt/conda/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 263, in propagate
    out = self.message(**msg_kwargs)
  File "/GPUFS/dlut_bcyin_1/ymq/space/github_private/gnnzoo/tu/conv.py", line 43, in message
    return self.fea_mlp(feature2d)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 94, in forward
    return F.relu(input, inplace=self.inplace)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 1063, in relu
    result = torch.relu(input)
RuntimeError: CUDA out of memory. Tried to allocate 540.00 MiB (GPU 0; 15.75 GiB total capacity; 13.82 GiB already allocated; 480.62 MiB free; 14.19 GiB reserved in total by PyTorch)
